import { Document, Page, Text, View, StyleSheet, Link } from "@react-pdf/renderer";
import type { ReportSummary } from "@/lib/types/app";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a" },
  brand: { fontSize: 10, color: "#7c3aed", marginBottom: 4, fontFamily: "Helvetica-Bold" },
  title: { fontSize: 20, marginBottom: 14, fontFamily: "Helvetica-Bold" },
  sectionTitle: { fontSize: 13, marginTop: 18, marginBottom: 8, fontFamily: "Helvetica-Bold", color: "#111827" },
  tldr: { fontSize: 12, lineHeight: 1.5, padding: 12, backgroundColor: "#f5f3ff", borderRadius: 4 },
  bullet: { flexDirection: "row", marginBottom: 6 },
  bulletDot: { width: 14, fontSize: 11 },
  bulletText: { flex: 1, lineHeight: 1.4 },
  source: { fontSize: 10, color: "#2563eb", marginBottom: 4 },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 9, color: "#9ca3af", textAlign: "center" },
});

export function ResearchReportDocument({ title, report }: { title: string; report: ReportSummary }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>MicroManus · Deep Research Report</Text>
        <Text style={styles.title}>{title}</Text>

        <Text style={styles.sectionTitle}>TL;DR</Text>
        <Text style={styles.tldr}>{report.tldr}</Text>

        <Text style={styles.sectionTitle}>Key Findings</Text>
        {report.key_findings.map((f, i) => (
          <View style={styles.bullet} key={i}>
            <Text style={styles.bulletDot}>{i + 1}.</Text>
            <Text style={styles.bulletText}>{f}</Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>Recommendations</Text>
        {report.recommendations.map((r, i) => (
          <View style={styles.bullet} key={i}>
            <Text style={styles.bulletDot}>→</Text>
            <Text style={styles.bulletText}>{r}</Text>
          </View>
        ))}

        {report.sources.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Sources</Text>
            {report.sources.map((s, i) => (
              <Link key={i} src={s.url} style={styles.source}>
                {i + 1}. {s.title || s.url}
              </Link>
            ))}
          </>
        )}

        <Text style={styles.footer} fixed>
          Generated by MicroManus — DrDroid's deep research agent
        </Text>
      </Page>
    </Document>
  );
}
